apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: gitlab-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: $IMAGE_TAG
        ports:
        - containerPort: 80
#      imagePullSecrets:  # Add this field if not present
#      - name: gitlab-registry-secret  # The name of the secret you created